#!/usr/bin/env python3

'''
   Turn kicad netlist files into SystemC source code
   =================================================
'''

import sys
import os

class SrcFile():
    ''' A C(++) language source file to be written '''
    def __init__(self, filename):
        self.filename = filename
        self.text = []
        self.includes = []

    def write(self, text):
        ''' ... '''
        self.text.append(text)

    def __iter__(self):
        yield self.filename
        for incl in self.includes:
            if isinstance(incl, SrcFile):
                yield from incl
            elif incl == "Chassis/planes.hh":
                yield incl
                yield "Chassis/plane_tbl.h"
            else:
                yield incl

    def include(self, target):
        ''' ... '''
        self.includes.append(target)
        if isinstance(target, SrcFile):
            self.text.append('#include "' + target.filename + '"\n')
        else:
            self.text.append('#include "' + target + '"\n')

    def commit(self):
        ''' ... '''
        ident = os.path.basename(sys.argv[0])
        suff = self.filename.split(".")[-1]
        prefix, suffix = {
            "h": ("/* ", " */\n"),
            "hh": ("/* ", " */\n"),
            "cc": ("/* ", " */\n"),
            "inc": ("# ", "\n"),
        }[suff]
        self.text.insert(
            0,
            prefix + "THIS FILE IS MACHINE GENERATED by " + ident + suffix,
        )
        now = "".join(self.text)
        try:
            was = open(self.filename, "r").read()
        except FileNotFoundError:
            was = ""
        if was != now:
            print("Changed:", self.filename)
            open(self.filename, "w").write(now)
