SHLIB = components
SHLIB_MAJOR = 1
WARNS ?= 3
MAN =
CXXFLAGS += -I/usr/local/include
CXXFLAGS += -I../SystemC
CXXFLAGS += -I../SystemC/diagproc
CXXFLAGS += -I../Planes
CXXFLAGS += -I../Diag
CXXFLAGS += -I../Infra
LDFLAGS += -L/usr/local/lib
LDFLAGS += -lsystemc

# CPUs
SRCS += 68020.cc
SRCS += 8051.cc

# Memory
SRCS += 16KX4.cc
SRCS += 1MEG.cc
SRCS += 2149.cc
SRCS += 2167.cc
SRCS += 28256.cc
SRCS += 2KX8.cc
SRCS += 64KX1.cc
SRCS += P2K8R.cc
SRCS += PAxxx.cc
SRCS += PBxxx.cc

# Misc
SRCS += 1489.cc
SRCS += 25S10.cc
SRCS += 25S558.cc
SRCS += 2661B.cc
SRCS += 2681.cc
SRCS += 58167.cc
SRCS += 8641.cc
SRCS += 93S48.cc
SRCS += DLY_35.cc
SRCS += LS125.cc

# F%d
SRCS += F00.cc
SRCS += F02.cc
SRCS += F04.cc
SRCS += F08.cc
SRCS += F10.cc
SRCS += F20.cc
SRCS += F30.cc
SRCS += F37.cc
SRCS += F38.cc
SRCS += F40.cc
SRCS += F51.cc
SRCS += F64.cc
SRCS += F74.cc
SRCS += F85.cc
SRCS += F86.cc
SRCS += F113.cc
SRCS += F133.cc
SRCS += F138.cc
SRCS += F139.cc
SRCS += F148.cc
SRCS += F151.cc
SRCS += F153.cc
SRCS += F157.cc
SRCS += F158.cc
SRCS += F163.cc
SRCS += F169.cc
SRCS += F174.cc
SRCS += F175.cc
SRCS += F181.cc
SRCS += F182.cc
SRCS += F189.cc
SRCS += F194.cc
SRCS += F240.cc
SRCS += F244.cc
#SRCS += F245.cc
SRCS += F245AB.cc
SRCS += F245BA.cc
SRCS += F251.cc
SRCS += F257.cc
SRCS += F258.cc
SRCS += F260.cc
SRCS += F280.cc
SRCS += F283.cc
SRCS += F299.cc
SRCS += F373.cc
SRCS += F374.cc
SRCS += F381.cc
SRCS += F521.cc
SRCS += F579.cc
SRCS += F652.cc

# PALs
SRCS += BUSPAL.cc
SRCS += CMDPAL.cc
SRCS += CNTRPAL.cc
SRCS += DIBRPAL.cc
SRCS += DISTPAL.cc
SRCS += DRADPAL.cc
SRCS += DRCPAL.cc
SRCS += LUXXPAL.cc
SRCS += MARPAL.cc
SRCS += MUXLPAL.cc
SRCS += NOVRAM.cc
SRCS += PHITPAL.cc
SRCS += RDRPAL.cc
SRCS += SETPAL.cc
SRCS += TAGAPAL.cc
SRCS += TPARPAL.cc
SRCS += TRACPAL.cc
SRCS += TSCPAL.cc
SRCS += TSXXPAL.cc

.include <bsd.lib.mk>
