// Machine-generated, see R1000.HwDoc/ImageProcessing/Chipdesc/chip.py
#define XWCSRAM_PIN_WE pin31
#define XWCSRAM_PIN_D0 pin1
#define XWCSRAM_PIN_Q0 pin2
#define XWCSRAM_PIN_D1 pin3
#define XWCSRAM_PIN_Q1 pin4
#define XWCSRAM_PIN_D2 pin5
#define XWCSRAM_PIN_Q2 pin6
#define XWCSRAM_PIN_D3 pin7
#define XWCSRAM_PIN_Q3 pin8
#define XWCSRAM_PIN_D4 pin9
#define XWCSRAM_PIN_Q4 pin10
#define XWCSRAM_PIN_D5 pin11
#define XWCSRAM_PIN_Q5 pin12
#define XWCSRAM_PIN_D6 pin13
#define XWCSRAM_PIN_Q6 pin14
#define XWCSRAM_PIN_D7 pin15
#define XWCSRAM_PIN_Q7 pin16
#define XWCSRAM_PIN_A0 pin17
#define XWCSRAM_PIN_A1 pin18
#define XWCSRAM_PIN_A2 pin19
#define XWCSRAM_PIN_A3 pin20
#define XWCSRAM_PIN_A4 pin21
#define XWCSRAM_PIN_A5 pin22
#define XWCSRAM_PIN_A6 pin23
#define XWCSRAM_PIN_A7 pin24
#define XWCSRAM_PIN_A8 pin25
#define XWCSRAM_PIN_A9 pin26
#define XWCSRAM_PIN_A10 pin27
#define XWCSRAM_PIN_A11 pin28
#define XWCSRAM_PIN_A12 pin29
#define XWCSRAM_PIN_A13 pin30
#ifdef ANON_PINS
    #define PIN_WE XWCSRAM_PIN_WE
    #define PIN_D0 XWCSRAM_PIN_D0
    #define PIN_Q0 XWCSRAM_PIN_Q0
    #define PIN_D1 XWCSRAM_PIN_D1
    #define PIN_Q1 XWCSRAM_PIN_Q1
    #define PIN_D2 XWCSRAM_PIN_D2
    #define PIN_Q2 XWCSRAM_PIN_Q2
    #define PIN_D3 XWCSRAM_PIN_D3
    #define PIN_Q3 XWCSRAM_PIN_Q3
    #define PIN_D4 XWCSRAM_PIN_D4
    #define PIN_Q4 XWCSRAM_PIN_Q4
    #define PIN_D5 XWCSRAM_PIN_D5
    #define PIN_Q5 XWCSRAM_PIN_Q5
    #define PIN_D6 XWCSRAM_PIN_D6
    #define PIN_Q6 XWCSRAM_PIN_Q6
    #define PIN_D7 XWCSRAM_PIN_D7
    #define PIN_Q7 XWCSRAM_PIN_Q7
    #define PIN_A0 XWCSRAM_PIN_A0
    #define PIN_A1 XWCSRAM_PIN_A1
    #define PIN_A2 XWCSRAM_PIN_A2
    #define PIN_A3 XWCSRAM_PIN_A3
    #define PIN_A4 XWCSRAM_PIN_A4
    #define PIN_A5 XWCSRAM_PIN_A5
    #define PIN_A6 XWCSRAM_PIN_A6
    #define PIN_A7 XWCSRAM_PIN_A7
    #define PIN_A8 XWCSRAM_PIN_A8
    #define PIN_A9 XWCSRAM_PIN_A9
    #define PIN_A10 XWCSRAM_PIN_A10
    #define PIN_A11 XWCSRAM_PIN_A11
    #define PIN_A12 XWCSRAM_PIN_A12
    #define PIN_A13 XWCSRAM_PIN_A13
#endif
