/*
 * Download order for LOAD_CONTROL_STORE_200.VAL
 */

#define VAL_WCS_A_0()		BITPOS(0, 0, 1)
#define VAL_WCS_A_1()		BITPOS(0, 1, 1)
#define VAL_WCS_A_2()		BITPOS(0, 2, 1)
#define VAL_WCS_A_3()		BITPOS(0, 3, 1)
#define VAL_WCS_A_4()		BITPOS(0, 4, 1)
#define VAL_WCS_A_5()		BITPOS(0, 5, 1)
#define VAL_WCS_B_0()		BITPOS(0, 6, 1)
#define VAL_WCS_B_1()		BITPOS(0, 7, 1)

#define VAL_WCS_B_2()		BITPOS(1, 0, 1)
#define VAL_WCS_B_3()		BITPOS(1, 1, 1)
#define VAL_WCS_B_4()		BITPOS(1, 2, 1)
#define VAL_WCS_B_5()		BITPOS(1, 3, 1)
#define VAL_WCS_FRAME_0()	BITPOS(1, 4, 1)
#define VAL_WCS_FRAME_1()	BITPOS(1, 5, 1)
#define VAL_WCS_FRAME_2()	BITPOS(1, 6, 1)
#define VAL_WCS_FRAME_3()	BITPOS(1, 7, 1)

#define VAL_WCS_FRAME_4()	BITPOS(2, 0, 1)
#define VAL_WCS_C_MUX_SEL_0()	BITPOS(2, 1, 1)
#define VAL_WCS_C_MUX_SEL_1()	BITPOS(2, 2, 1)
#define VAL_WCS_PARITY()	BITPOS(2, 3, 1)
#define VAL_WCS_RAND_0()	BITPOS(2, 4, 1)
#define VAL_WCS_RAND_1()	BITPOS(2, 5, 1)
#define VAL_WCS_RAND_2()	BITPOS(2, 6, 1)
#define VAL_WCS_RAND_3()	BITPOS(2, 7, 1)

#define VAL_WCS_C_0()		BITPOS(3, 0, 0)
#define VAL_WCS_C_1()		BITPOS(3, 1, 0)
#define VAL_WCS_C_2()		BITPOS(3, 2, 0)
#define VAL_WCS_C_3()		BITPOS(3, 3, 0)
#define VAL_WCS_C_4()		BITPOS(3, 4, 0)
#define VAL_WCS_C_5()		BITPOS(3, 5, 0)
#define VAL_WCS_M_A_SRC_0()	BITPOS(3, 6, 0)
#define VAL_WCS_M_A_SRC_1()	BITPOS(3, 7, 0)

#define VAL_WCS_M_B_SRC_0()	BITPOS(4, 0, 0)
#define VAL_WCS_M_B_SRC_1()	BITPOS(4, 1, 0)
#define VAL_WCS_ALU_FUNC_0()	BITPOS(4, 2, 0)
#define VAL_WCS_ALU_FUNC_1()	BITPOS(4, 3, 0)
#define VAL_WCS_ALU_FUNC_2()	BITPOS(4, 4, 0)
#define VAL_WCS_ALU_FUNC_3()	BITPOS(4, 5, 0)
#define VAL_WCS_ALU_FUNC_4()	BITPOS(4, 6, 0)
#define VAL_WCS_C_SOURCE()	BITPOS(4, 7, 0)

#define VAL_WCS_LENGTH_SRC()	BITPOS(5, 0, 0)
#define VAL_WCS_OFFS_SRC()	BITPOS(5, 1, 0)
